### ISSUE TITLE
建议对规则做整合，合并成一份文件

### ISSUE THREAD

**Issue by 217heidai** [Silentely/AdBlock-Acceleration#7]
建议对规则做整合，合并成一份文件。市面上去广告规则比较多，逐个添加比较麻烦，另外规则中其实也有不少是重复的。

**Comment by Silentely** [comment]
整合带来的是，一个是文件过大 对于想单独定制的人和部分客户端软件带来的是影响上网体验。其次是部分规则的格式并不是统一的。其实HalfLife和Adgk的规则是专为国内环境整合的。你需要的的话可以只订阅这两个其中一个或者两个都订阅

**Comment by Silentely** [comment]
> 建议对规则做整合，合并成一份文件。市面上去广告规则比较多，逐个添加比较麻烦，另外规则中其实也有不少是重复的。
